In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
import pandas as pd

hdi_data= pd.read_excel('hdi.xlsx')
disaster_data= pd.read_excel('disasters.xlsx')
conflicts_data = pd.read_excel('conflicts.xlsx')

aggregated_disaster_data = disaster_data.groupby(['Country', 'Year']).agg({
    "AID Contribution ('000 US$)": 'sum',
    'Total Deaths': 'sum',
    'No. Injured': 'sum',
    'No. Affected': 'sum',
    'No. Homeless': 'sum',
    'Total Affected': 'sum',
    "Total Damage, Adjusted ('000 US$)": 'sum',
    'Disaster Group': lambda x: ', '.join(sorted(set(x))),
    'Disaster Type': lambda x: ', '.join(sorted(set(x)))
}).reset_index()

aggregated_conflicts_data = conflicts_data.groupby(['Country', 'Year']).agg({
    "Best Fatalities Estimate": 'sum'}).reset_index()

          Country  Year  Best Fatalities Estimate
0     Afghanistan  1989                      5411
1     Afghanistan  1990                      1514
2     Afghanistan  1991                      3553
3     Afghanistan  1992                      4385
4     Afghanistan  1993                      4105
...           ...   ...                       ...
1973     Zimbabwe  2011                         1
1974     Zimbabwe  2012                         1
1975     Zimbabwe  2018                         4
1976     Zimbabwe  2019                         8
1977     Zimbabwe  2020                         2

[1978 rows x 3 columns]

In [13]:
hdi_disasters = pd.merge(hdi_data, aggregated_disaster_data, on = ['Country', 'Year'], how = 'left')

final_merged = pd.merge(hdi_disasters, aggregated_conflicts_data, on = ['Country', 'Year'], how = 'left')

final_merged.to_excel('final_merged.xlsx', index = False)